### ISSUE TITLE
[CI] Add github CI for keymanager

### ISSUE THREAD

**Issue by dracarys18** [juspay/hyperswitch-encryption-service#27]
## Description
Add a CI to check formatting, compilation and clippy

## Implementation
Refer 
- [Hyperswitch CI - PR](https://github.com/juspay/hyperswitch/blob/main/.github/workflows/CI-pr.yml)
- [Hyperswitch CI - Push to main](https://github.com/juspay/hyperswitch/blob/main/.github/workflows/CI-push.yml)

**Comment by notnick2** [comment]
Hey added a CI workflow configuration in .github/workflows/ci.yml.
which checks formatting, compilation and clippy. 

I have created a pull request to address this issue https://github.com/juspay/hyperswitch-encryption-service/pull/28

**Comment by gorakhnathy7** [comment]
Hey @notnick2 
Thanks for participating!
Kindly fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSe3rhgbf5KMx7Qoz0uPxUQeodvtavoXcqzCnZGm9N8n0ZjKtQ/viewform) once all of your PRs are merged.

**Comment by notnick2** [comment]
I have submitted the PR submission form 6 days ago and hasn't received any
email as mentioned in the form could you please verify it

Thanks for rewarding open source contributors for their contribution,
juspay is truly an amazing fintech organization
looking forward for a response

**Comment by gorakhnathy7** [comment]
Hey @notnick2 We will rolling out goodies after Hacktoberfest is over!

I'll send you a confirmation soon.

**Comment by notnick2** [comment]
thanks for your quick action looking forward to contribute much more at hyperswitch!
