### ISSUE TITLE
Data Key versioning isn't working for multiple create requests

### ISSUE THREAD

**Issue by akhildevelops** [juspay/hyperswitch-encryption-service#30]
New versions of data keys aren't stored in Database for new data key creation requests.

For first time data key is inserted into DB from the request
```shell
POST http://localhost:5000/key/create
Accept: application/json+text/plain
Content-Type: application/json

{
    "data_identifier":"User",
    "key_identifier":"Akhil"
}
```
![image](https://github.com/user-attachments/assets/2c3c5d2a-f6b7-47ea-8de3-f6a4105f390c)

But for later requests on same key and data identifiers new encryption keys aren't stored in the database with version increment.  Even after cache expiry

**Comment by akhildevelops** [comment]
I'll address this issue in my https://github.com/juspay/hyperswitch-encryption-service/pull/29

**Comment by dracarys18** [comment]
@akhildevelops The first create will create the key in the DB and the second request would just get the key which was created in the previous request. To rotate a key use `/key/rotate`
